version: '3'

services:
  app:
    build: .
    command: yarn prod
    container_name: news-feed-server
    ports:
      - 5566:5566
    volumes:
      - .:/usr/app
      - /usr/app/node_modules/

# docker exec -it <container-id> //bin//sh

# to start: docker-compose -f docker-compose.yml -f docker-compose-prod.yml up
