version: '3'

services:
  app:
    build: .
    container_name: news-feed-server
    ports:
      - 5566:5566
    volumes:
      - .:/usr/app
      - /usr/app/node_modules/bcrypt

# docker exec -it <container-id> //bin//sh
